# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ed1d8e9b6fb31a0ad1e143d08a9e31cdd90ef4cf1e7b0ef2938f766d607ee8a8ab01cfbec586f775c7787407e528960758556b7f10a9bbf4e665b1c401c2eb

test:
  secret_key_base: 3130675e0212665dc059c4233739278ec273a916a832d1c71645a8e978ef61f246bcb44dc110ac6abee946e6391bd341744edccf72c67414d45ea1ba2229ef71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
